"""empty message

Revision ID: 0164756aabcf
Revises: 61224426a119
Create Date: 2022-07-15 08:42:32.682960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0164756aabcf'
down_revision = '61224426a119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Chore_name_key', 'Chore', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Chore_name_key', 'Chore', ['name'])
    # ### end Alembic commands ###
