"""empty message

Revision ID: 09f0f82b2e6b
Revises: 1ec0679ba4d0
Create Date: 2022-07-13 12:29:28.651422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09f0f82b2e6b'
down_revision = '1ec0679ba4d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Chore', 'duration',
               existing_type=sa.INTEGER(),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Chore', 'duration',
               existing_type=sa.Time(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
