"""empty message

Revision ID: 0fa0228ce4f6
Revises: 691453b48992
Create Date: 2022-07-12 08:51:04.919640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa0228ce4f6'
down_revision = '691453b48992'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Chore_user_id_fkey', 'Chore', type_='foreignkey')
    op.drop_column('Chore', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chore', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Chore_user_id_fkey', 'Chore', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###
