"""empty message

<<<<<<< HEAD:migrations/versions/8731e7ab0fba_.py
Revision ID: 8731e7ab0fba
Revises: 
Create Date: 2022-08-01 12:41:38.382513
=======
<<<<<<<< HEAD:migrations/versions/e679f718233b_.py
Revision ID: e679f718233b
Revises: 
Create Date: 2022-07-30 09:23:28.074984
========
Revision ID: 8e970e7b1528
Revises: 
Create Date: 2022-07-30 10:45:54.889865
>>>>>>>> origin/development:migrations/versions/8e970e7b1528_.py
>>>>>>> development:migrations/versions/8e970e7b1528_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/8731e7ab0fba_.py
revision = '8731e7ab0fba'
=======
<<<<<<<< HEAD:migrations/versions/e679f718233b_.py
revision = 'e679f718233b'
========
revision = '8e970e7b1528'
>>>>>>>> origin/development:migrations/versions/8e970e7b1528_.py
>>>>>>> development:migrations/versions/8e970e7b1528_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('Chore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('duration', sa.Time(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('UsersInTeam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=80), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UsersInTeam')
    op.drop_table('Chore')
    op.drop_table('User')
    op.drop_table('Team')
    # ### end Alembic commands ###
