"""empty message

Revision ID: eb2c57231477
Revises: cd4358c237d8
Create Date: 2022-07-23 10:37:17.295223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb2c57231477'
down_revision = 'cd4358c237d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UsersInTeam', sa.Column('team_name', sa.String(length=80), nullable=False))
    op.drop_constraint('UsersInTeam_team_id_fkey', 'UsersInTeam', type_='foreignkey')
    op.drop_column('UsersInTeam', 'team_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UsersInTeam', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('UsersInTeam_team_id_fkey', 'UsersInTeam', 'Team', ['team_id'], ['id'])
    op.drop_column('UsersInTeam', 'team_name')
    # ### end Alembic commands ###
