"""empty message

Revision ID: ffb1e84fb9e3
Revises: 9c86a1b79cfa
Create Date: 2022-07-12 18:05:04.689945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb1e84fb9e3'
down_revision = '9c86a1b79cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Chore', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Chore', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Chore', type_='foreignkey')
    op.drop_column('Chore', 'user_id')
    # ### end Alembic commands ###
